// app/(protected)/dashboard/DashboardClient.tsx
"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSupabase } from "@/app/components/SupabaseSessionProvider";
import { useUserPlan } from "@/app/components/useUserPlan";
import type { DashboardData } from "./page";
import { PRICING } from "@/app/lib/pricing";
import { useTranslation } from "@/app/components/I18nProvider";

// ── Helpers ───────────────────────────────────────────────────────────────────

function titleOrUntitled(title: string | null, fallback: string) {
  return title?.trim() ? title.trim() : fallback;
}

function friendlyNameFromUser(user: any): string | null {
  const md = user?.user_metadata ?? {};
  // Auto-generated usernames look like "xidohi8055" — all lowercase letters then digits, no spaces
  const isAutoGenerated = (s: string) => /^[a-z]+\d+$/i.test(s.trim()) && !s.includes(" ");
  const emailPrefix = user?.email ? String(user.email).split("@")[0] : null;
  const raw = [
    md.full_name,
    md.name,
    md.display_name,
    isAutoGenerated(String(md.username ?? "")) ? null : md.username,
    emailPrefix && isAutoGenerated(emailPrefix) ? null : emailPrefix,
  ].filter(Boolean).map(String)[0] ?? "";
  const clean = raw.trim().replace(/\s+/g, " ").slice(0, 24);
  return clean || null;
}

function buildHref(prompt: string) {
  return `/journal/new?prompt=${encodeURIComponent(prompt)}`;
}

function greetingByHour(t: { dashboard: { goodMorning: string; goodAfternoon: string; goodEvening: string } }) {
  const h = new Date().getHours();
  if (h < 12) return t.dashboard.goodMorning;
  if (h < 18) return t.dashboard.goodAfternoon;
  return t.dashboard.goodEvening;
}

function friendlyDate(iso: string, isMounted = false, t?: { dashboard: { today: string; yesterday: string } }) {
  const d = new Date(iso);
  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(today.getDate() - 1);
  const isoDate = (x: Date) => x.toISOString().slice(0, 10);
  if (isoDate(d) === isoDate(today)) return t?.dashboard.today ?? "today";
  if (isoDate(d) === isoDate(yesterday)) return t?.dashboard.yesterday ?? "yesterday";
  return isMounted ? d.toLocaleDateString(undefined, { month: "short", day: "numeric" }) : iso.slice(0, 10);
}

function startOfNextMonth() {
  const d = new Date();
  return new Date(d.getFullYear(), d.getMonth() + 1, 1)
    .toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

// Sanitise AI-generated corepattern — strip anything that references test data
// or looks like a raw NLP analysis sentence rather than a human-readable insight.
function sanitiseCorePattern(raw: string | null): string | null {
  if (!raw) return null;
  // If the pattern contains typical test-data markers, suppress it
  const lower = raw.toLowerCase();
  if (
    lower.includes("for test") ||
    lower.includes("as indicated by") ||
    lower.includes("your phrase") ||
    lower.length < 15
  ) {
    return null;
  }
  return raw;
}

// Prompts are defined in t.dashboard.prompts (app/lib/i18n/)

function getDailyPrompts<T extends { q: string; sub: string; accent: string }>(
  pool: readonly T[]
): [T, T, T] {
  const day = new Date().getDay();
  const start = day % pool.length;
  return [
    pool[start % pool.length],
    pool[(start + 1) % pool.length],
    pool[(start + 2) % pool.length],
  ] as [T, T, T];
}

// Map accent name → Tailwind classes
const ACCENT_CLASSES: Record<string, { border: string; label: string; dot: string; arrow: string }> = {
  emerald: {
    border: "border-qm-positive-border hover:border-qm-positive",
    label: "text-qm-positive",
    dot: "bg-qm-positive-strong",
    arrow: "text-qm-positive group-hover:text-qm-positive-hover",
  },
  violet: {
    border: "border-qm-premium-border hover:border-qm-premium",
    label: "text-qm-premium",
    dot: "bg-qm-premium-strong",
    arrow: "text-qm-premium group-hover:text-qm-premium-hover",
  },
  amber: {
    border: "border-qm-warning-border hover:border-qm-warning",
    label: "text-qm-warning",
    dot: "bg-qm-warning-strong",
    arrow: "text-qm-warning group-hover:text-qm-warning-hover",
  },
  sky: {
    border: "border-qm-premium-border hover:border-qm-premium",
    label: "text-qm-premium",
    dot: "bg-qm-premium-strong",
    arrow: "text-qm-premium group-hover:text-qm-premium-hover",
  },
  rose: {
    border: "border-qm-danger-border hover:border-qm-danger",
    label: "text-qm-danger",
    dot: "bg-qm-danger-strong",
    arrow: "text-qm-danger group-hover:text-qm-danger-hover",
  },
  slate: {
    border: "border-qm-border-subtle hover:border-qm-border-subtle",
    label: "text-qm-faint",
    dot: "bg-qm-muted",
    arrow: "text-qm-muted group-hover:text-qm-secondary",
  },
};

// ── Sub-components ────────────────────────────────────────────────────────────

// ── Premium insight card ──────────────────────────────────────────────────────

function PremiumInsightCard({
  emotion,
  theme,
  corepattern,
  reflectedThisWeek,
}: {
  emotion: string | null;
  theme: string | null;
  corepattern: string | null;
  reflectedThisWeek: boolean;
}) {
  const safePattern = sanitiseCorePattern(corepattern);
  const hasData = emotion || theme || safePattern;
  if (!hasData) return null;

  const bodyText = safePattern
    ? safePattern
    : emotion && theme
    ? `${emotion} keeps showing up — often alongside themes of ${theme.toLowerCase()}.`
    : emotion
    ? `${emotion} has been your most present emotion recently.`
    : `${theme} is the theme appearing most in your entries.`;

  return (
    <div className="rounded-2xl border border-qm-positive-border bg-gradient-to-br from-qm-positive-strong/[0.06] to-transparent p-5 sm:p-6">
      <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-positive">
        Your pattern right now
      </p>

      <p className="font-display text-base font-medium leading-relaxed text-qm-primary sm:text-[17px]">
        &ldquo;{bodyText}&rdquo;
      </p>

      {(emotion || theme) && (
        <div className="mt-3 flex flex-wrap gap-2">
          {emotion && (
            <span className="rounded-full border border-qm-premium-border bg-qm-premium-soft px-2.5 py-0.5 text-xs text-qm-premium">
              {emotion}
            </span>
          )}
          {theme && (
            <span className="rounded-full border border-qm-positive-border bg-qm-positive-soft px-2.5 py-0.5 text-xs text-qm-positive">
              {theme}
            </span>
          )}
        </div>
      )}

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Link
          href="/insights"
          className="text-xs font-medium text-qm-positive transition hover:text-qm-positive-hover"
        >
          See full insights →
        </Link>
        {!reflectedThisWeek && (
          <>
            <span className="text-xs text-qm-faint">·</span>
            <Link
              href="/journal"
              className="text-xs text-qm-faint transition hover:text-qm-muted"
            >
              Reflect on a recent entry
            </Link>
          </>
        )}
      </div>
    </div>
  );
}

// ── Free insight teaser ───────────────────────────────────────────────────────

function FreeInsightTeaser({
  entryCount,
  emotion,
  theme,
}: {
  entryCount: number;
  emotion: string | null;
  theme: string | null;
}) {
  const { t } = useTranslation();
  const hasHint = emotion || theme;

  if (entryCount < 3) {
    return (
      <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5 sm:p-6">
        <p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-faint">
          Your patterns
        </p>
        <p className="text-sm leading-relaxed text-qm-muted">
          Write{" "}
          <span className="text-qm-primary">
            {t.dashboard.moreEntries(3 - entryCount)}
          </span>{" "}
          and Quiet Mirror will start noticing what quietly repeats across your writing.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5 sm:p-6">
      <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-faint">
        {t.dashboard.patternForming}
      </p>

      {hasHint ? (
        <p className="text-sm leading-relaxed text-qm-secondary">
          {t.dashboard.patternTeaser.split("{theme}")[0]}
          <span className="select-none rounded bg-white/10 px-1 text-qm-primary blur-[5px]">
            {emotion ?? theme}
          </span>
          {t.dashboard.patternTeaser.split("{theme}")[1]}
        </p>
      ) : (
        <p className="text-sm leading-relaxed text-qm-secondary">
          {t.dashboard.patternTeaserNoHint}
        </p>
      )}

      <Link
        href="/upgrade"
        className="mt-4 inline-flex items-center gap-1.5 rounded-full bg-qm-accent px-4 py-2 text-xs font-semibold text-white transition hover:bg-qm-accent-hover"
      >
        {t.dashboard.unlockInsights}
      </Link>
    </div>
  );
}

// ── Thread card ───────────────────────────────────────────────────────────────

function ThreadCard({
  lastEntryId,
  lastEntryTitle,
  lastEntryDate,
  lastTopEmotion,
  wroteToday,
}: {
  lastEntryId: string | null;
  lastEntryTitle: string | null;
  lastEntryDate: string | null;
  lastTopEmotion: string | null;
  wroteToday: boolean;
}) {
  const { t } = useTranslation();
  const [mounted, setMounted] = useState(false);
  useEffect(() => { setMounted(true); }, []);
  const when = lastEntryDate ? friendlyDate(lastEntryDate, mounted, t) : null;
  const title = titleOrUntitled(lastEntryTitle, t.journal.untitledEntry);

  const sectionLabel = wroteToday
    ? t.dashboard.wroteToday
    : lastEntryId
    ? t.dashboard.pickUpThread
    : t.dashboard.startHere;

  // Don't echo the raw entry title into the prompt body — feels broken with test titles
  const body = wroteToday
    ? t.dashboard.dayEvolved
    : lastEntryId && lastTopEmotion
    ? `You wrote ${when}. ${lastTopEmotion} was present. Has anything shifted?`
    : lastEntryId
    ? `You last wrote ${when}. Has anything softened since?`
    : t.dashboard.oneHonestSentence;

  const threadPrompt = wroteToday
    ? t.dashboard.alreadyWroteToday
    : lastTopEmotion
    ? `Following up on your last entry — ${lastTopEmotion} was present. Has anything shifted?`
    : `Following up on your last entry — has anything softened since you wrote?`;

  return (
    <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5">
      <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-faint">
        {sectionLabel}
      </p>
      <p className="mt-2 text-sm font-medium leading-snug text-qm-primary">
        {body}
      </p>

      <div className="mt-4 flex flex-wrap gap-2">
        <Link
          href={buildHref(threadPrompt)}
          className="inline-flex rounded-full bg-qm-accent px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-qm-accent-hover"
        >
          {wroteToday ? t.dashboard.addToToday : t.dashboard.writeNow}
        </Link>

        {lastEntryId && (
          <Link
            href={`/journal/${lastEntryId}`}
            className="inline-flex rounded-full border border-white/[0.08] bg-white/[0.03] px-4 py-2 text-sm font-medium text-qm-secondary transition hover:bg-white/[0.07]"
          >
            {t.dashboard.openLastEntry}
          </Link>
        )}
      </div>
    </div>
  );
}

// ── Welcome panel (zero entries) ──────────────────────────────────────────────

function WelcomePanel() {
  const { t } = useTranslation();
  return (
    <div className="mb-8 rounded-2xl border border-qm-positive-border bg-qm-positive-strong/[0.04] p-6">
      <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-positive">
        Welcome to Quiet Mirror
      </p>
      <h2 className="font-display text-lg font-semibold leading-snug text-qm-primary">
        This is your private space to think out loud.
      </h2>
      <p className="mt-2 text-sm leading-relaxed text-qm-muted">
        Write what&apos;s actually going on — Quiet Mirror reads it, reflects it back
        gently, and starts noticing what quietly repeats across your entries over
        time. One sentence is always enough to start.
      </p>
      <Link
        href="/journal/new"
        className="mt-5 inline-flex items-center gap-2 rounded-full bg-qm-accent px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-qm-accent-hover"
      >
        Write your first entry →
      </Link>
      <p className="mt-3 text-xs text-qm-faint">
        Takes less than a minute · stays private · never trains AI
      </p>
    </div>
  );
}

// ── Pattern started (1 entry with reflection) ─────────────────────────────────

function PatternStartedCard({
  emotion,
  theme,
}: {
  emotion: string | null;
  theme: string | null;
}) {
  return (
    <div className="mb-8 rounded-2xl border border-qm-premium-border bg-qm-premium-strong/[0.04] p-6">
      <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-premium">
        Your pattern history has started
      </p>
      <p className="text-sm leading-relaxed text-qm-secondary">
        Quiet Mirror has your first reflection.{" "}
        {emotion || theme ? (
          <>
            It noticed{" "}
            <span className="text-qm-primary">{emotion ?? theme}</span> in what
            you wrote.{" "}
          </>
        ) : null}
        The more you write, the more clearly the patterns will show.
      </p>
      <Link
        href="/journal/new"
        className="mt-4 inline-flex items-center gap-2 text-xs font-medium text-qm-premium transition hover:text-qm-premium-hover"
      >
        Write another entry →
      </Link>
    </div>
  );
}

// ── Progress nudge (2–4 entries) ──────────────────────────────────────────────

function ProgressNudge({ entryCount }: { entryCount: number }) {
  const { t } = useTranslation();
  const remaining = 5 - entryCount;
  if (remaining <= 0) return null;

  return (
    <div className="mb-8 rounded-2xl border border-qm-border-subtle bg-qm-elevated p-5">
      <div className="mb-2 flex items-center justify-between">
        <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-faint">
          {t.dashboard.patternFormingYours}
        </p>
        <p className="text-xs text-qm-faint">
          {entryCount} / 5 entries
        </p>
      </div>
      <div className="mb-3 h-1 w-full rounded-full bg-qm-card">
        <div
          className="h-1 rounded-full bg-qm-positive-muted transition-all"
          style={{ width: `${(entryCount / 5) * 100}%` }}
        />
      </div>
      <p className="text-sm text-qm-muted">
        <span className="text-qm-primary">
          {t.dashboard.moreEntries(remaining)}
        </span>{" "}
        and Quiet Mirror will start showing you what quietly repeats across your
        writing.
      </p>
    </div>
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────

export default function DashboardClient({
   data }: { data: DashboardData }) {
  const { t } = useTranslation();
  const { supabase } = useSupabase();
  const { planType, credits, loading: planLoading } = useUserPlan();

  const [displayName, setDisplayName] = useState<string | null>(null);
  const [mounted, setMounted] = useState(false);
  useEffect(() => { setMounted(true); }, []);

  useEffect(() => {
    supabase.auth.getUser().then(({ data: d }) => {
      setDisplayName(friendlyNameFromUser(d?.user));
    });
  }, [supabase]);

  const isPremium = planType === "PREMIUM" || planType === "TRIAL";
  const isFree = !planLoading && planType === "FREE";
  const reflectionsPaused = isFree && (credits ?? 0) === 0;
  const resetLabel = startOfNextMonth();
  const readablePlan = isPremium
    ? planType === "TRIAL" ? t.dashboard.trial : t.dashboard.premium
    : t.dashboard.free;

  const greeting = displayName
    ? `${greetingByHour(t)}, ${displayName}`
    : greetingByHour(t);

  const prompts = useMemo(() => getDailyPrompts(t.dashboard.prompts), [t.dashboard.prompts]);

  const {
    entryCount, writingDays, lastEntryId, lastEntryTitle, lastEntryDate,
    lastEntryHasReflection, lastTopEmotion, lastTopTheme, lastCorepattern,
    wroteToday, reflectedThisWeek,
  } = data;

  const subline = useMemo(() => {
    if (entryCount === 0) return t.journal.emptyStateNudge;
    if (wroteToday) return t.dashboard.writtenToday;
    return t.dashboard.choosePrompt;
  }, [entryCount, wroteToday]);

  return (
    <div className="mx-auto max-w-5xl px-5 pb-20 pt-10 text-qm-primary sm:px-6">

      {/* ── Header ── */}
      <div className="mb-8">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="space-y-1">
            {/* ✅ Fraunces serif on the greeting — most personal line in the app */}
            <h1 className="font-display text-3xl font-semibold tracking-tight text-qm-primary sm:text-4xl">
              {greeting}
            </h1>
            <p className="text-sm text-qm-faint">{subline}</p>
          </div>
        </div>

        {/* ✅ Replaced debug-style pill badges with a subtle single-line status row */}
        <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-qm-faint">
          <span>
            Plan:{" "}
            <span className={isPremium ? "text-qm-positive" : "text-qm-muted"}>
              {readablePlan}
            </span>
          </span>

          <span className="text-qm-faint">·</span>

          {isPremium ? (
            <span>
              {t.dashboard.reflUnlimited}
            </span>
          ) : reflectionsPaused ? (
            <span>
              {t.dashboard.reflPaused(resetLabel)}
            </span>
          ) : (
            <span>
              {t.dashboard.reflRemaining}{" "}
              <span className="text-qm-muted">
                {planLoading ? "…" : String(credits ?? 0)}
              </span>
            </span>
          )}

          {entryCount > 0 && (
            <>
              <span className="text-qm-faint">·</span>
              <span>
                {entryCount} {entryCount === 1 ? t.dashboard.entry : t.dashboard.entries}
              </span>
            </>
          )}
        </div>

        {reflectionsPaused && (
          <p className="mt-1.5 text-xs text-qm-faint">
            You can always write freely — reflections return {resetLabel}.
          </p>
        )}

        {/* Bug #23 fix: upgrade CTA at 0-credit wall — highest-intent moment */}
        {reflectionsPaused && !isPremium && (
          <div className="mt-3 flex items-center gap-3">
            <Link
              href="/upgrade"
              className="inline-flex items-center rounded-full bg-qm-accent px-4 py-1.5 text-xs font-semibold text-white hover:bg-qm-accent-hover transition-colors"
            >
              Unlock unlimited reflections →
            </Link>
            <span className="text-xs text-qm-faint">{PRICING.trialDays}-day full refund · Cancel anytime</span>
          </div>
        )}
      </div>

      {/* ── Onboarding moments ── */}
      {entryCount === 0 && <WelcomePanel />}

      {entryCount === 1 && lastEntryHasReflection && (
        <PatternStartedCard emotion={lastTopEmotion} theme={lastTopTheme} />
      )}

      {entryCount >= 2 && entryCount < 5 && (
        <ProgressNudge entryCount={entryCount} />
      )}

      {/* ── Premium insight / Free teaser ── */}
      {isPremium && (lastTopEmotion || lastTopTheme || lastCorepattern) && (
        <div className="mb-8">
          <PremiumInsightCard
            emotion={lastTopEmotion}
            theme={lastTopTheme}
            corepattern={lastCorepattern}
            reflectedThisWeek={reflectedThisWeek}
          />
        </div>
      )}

      {isFree && entryCount >= 5 && (
        <div className="mb-8">
          <FreeInsightTeaser
            entryCount={entryCount}
            emotion={lastTopEmotion}
            theme={lastTopTheme}
          />
        </div>
      )}

      {/* ── Daily prompts ── */}
      <div className="mb-6">
        <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-faint">
          Today&apos;s prompts
        </p>

        <div className="grid gap-3 sm:grid-cols-3">
          {prompts.map((c) => {
            const ac = ACCENT_CLASSES[c.accent] ?? ACCENT_CLASSES.slate;
            return (
              <Link
                key={c.q}
                href={buildHref(c.q)}
                className={`group rounded-2xl border bg-white/[0.02] p-5 transition hover:bg-white/[0.05] ${ac.border}`}
              >
                {/* ✅ Colored dot per-prompt for visual differentiation */}
                <span className={`mb-3 block h-1.5 w-1.5 rounded-full ${ac.dot}`} />
                <p className="font-medium leading-snug text-qm-primary transition group-hover:text-qm-primary">
                  {c.q}
                </p>
                <p className="mt-1.5 text-xs leading-relaxed text-qm-faint">{c.sub}</p>
                <p className="mt-3 text-xs font-medium transition text-qm-positive group-hover:text-qm-positive-hover">
                  Start →
                </p>
              </Link>
            );
          })}
        </div>
      </div>

      {/* ── Thread + history row ── */}
      <div className="grid gap-4 sm:grid-cols-2">

        <ThreadCard
          lastEntryId={lastEntryId}
          lastEntryTitle={lastEntryTitle}
          lastEntryDate={lastEntryDate}
          lastTopEmotion={lastTopEmotion}
          wroteToday={wroteToday}
        />

        {/* ✅ History card — cleaner, less "settings panel" feel */}
        <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5">
          <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-qm-faint">
            Your history
          </p>

          <div className="mt-4 space-y-2.5">
            <div className="flex items-center justify-between text-sm">
              <span className="text-qm-faint">{t.dashboard.totalEntries}</span>
              <span className="font-medium text-qm-primary">{entryCount}</span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-qm-faint">{t.dashboard.writingDays}</span>
              <span className="font-medium text-qm-primary">{writingDays}</span>
            </div>
            {lastEntryDate && (
              <div className="flex items-center justify-between text-sm">
                <span className="text-qm-faint">{t.dashboard.lastEntryLabel}</span>
                <span className="font-medium text-qm-primary" suppressHydrationWarning>
                  {friendlyDate(lastEntryDate, mounted, t)}
                </span>
              </div>
            )}
            {isPremium && (
              <div className="flex items-center justify-between text-sm">
                <span className="text-qm-faint">{t.dashboard.reflLabel}</span>
                <span className="font-medium text-qm-positive">{t.dashboard.reflUnlimitedShort}</span>
              </div>
            )}
          </div>

          <div className="mt-5 flex flex-wrap gap-3 border-t border-white/[0.05] pt-4">
            <Link
              href="/journal"
              className="text-xs text-qm-faint transition hover:text-qm-secondary"
            >
              All entries →
            </Link>
            {isPremium && (
              <Link
                href="/insights"
                className="text-xs text-qm-positive transition hover:text-qm-positive-hover"
              >
                View insights →
              </Link>
            )}
          </div>
        </div>
      </div>

    </div>
  );
}
