/**
 * app/(protected)/dashboard/DashboardClient.tsx
 *
 * Client component for the main dashboard — the first screen users see after login.
 *
 * Responsibilities:
 * - Displays the AI pattern card (most prominent element post-redesign #138)
 * - Shows recent journal entries, writing streak, and credit status
 * - Handles the "Write now" CTA and today's entry detection
 * - Reads plan type from useUserPlan() to conditionally show upgrade prompts
 * - Receives pre-fetched DashboardData from the server page component
 */
// app/(protected)/dashboard/DashboardClient.tsx
"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSupabase } from "@/app/components/SupabaseSessionProvider";
import { useUserPlan } from "@/app/components/useUserPlan";
import type { DashboardData } from "./page";
import { PRICING } from "@/app/lib/pricing";
import { CONFIG } from "@/app/lib/config";
import { useTranslation } from "@/app/components/I18nProvider";
import type { User } from "@supabase/supabase-js";

// ── Helpers ───────────────────────────────────────────────────────────────────

function titleOrUntitled(title: string | null, fallback: string) {
  return title?.trim() ? title.trim() : fallback;
}

function friendlyNameFromUser(user: User | null): string | null {
  const md = user?.user_metadata ?? {};
  const isAutoGenerated = (s: string) => /^[a-z]+\d+$/i.test(s.trim()) && !s.includes(" ");
  const emailPrefix = user?.email ? String(user.email).split("@")[0] : null;
  const raw = [
    md.full_name, md.name, md.display_name,
    isAutoGenerated(String(md.username ?? "")) ? null : md.username,
    emailPrefix && isAutoGenerated(emailPrefix) ? null : emailPrefix,
  ].filter(Boolean).map(String)[0] ?? "";
  const clean = raw.trim().replace(/\s+/g, " ").slice(0, 24);
  return clean || null;
}

function buildHref(prompt: string) {
  return `/journal/new?prompt=${encodeURIComponent(prompt)}`;
}

function greetingByHour(t: { dashboard: { goodMorning: string; goodAfternoon: string; goodEvening: string } }) {
  const h = new Date().getHours();
  if (h < 12) return t.dashboard.goodMorning;
  if (h < 18) return t.dashboard.goodAfternoon;
  return t.dashboard.goodEvening;
}

function friendlyDate(iso: string, isMounted = false, t?: { dashboard: { today: string; yesterday: string } }) {
  const d = new Date(iso);
  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(today.getDate() - 1);
  const isoDate = (x: Date) => x.toISOString().slice(0, 10);
  if (isoDate(d) === isoDate(today)) return t?.dashboard.today ?? "today";
  if (isoDate(d) === isoDate(yesterday)) return t?.dashboard.yesterday ?? "yesterday";
  return isMounted ? d.toLocaleDateString(undefined, { month: "short", day: "numeric" }) : iso.slice(0, 10);
}

function startOfNextMonth() {
  const d = new Date();
  return new Date(d.getFullYear(), d.getMonth() + 1, 1)
    .toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

function sanitiseCorePattern(raw: string | null): string | null {
  if (!raw) return null;
  const lower = raw.toLowerCase();
  if (
    lower.includes("for test") ||
    lower.includes("as indicated by") ||
    lower.includes("your phrase") ||
    lower.length < 15
  ) return null;
  return raw;
}

function getDailyPrompts<T extends { q: string; sub: string; accent: string }>(
  pool: readonly T[]
): [T, T] {
  const day = new Date().getDay();
  const start = day % pool.length;
  return [pool[start % pool.length], pool[(start + 1) % pool.length]] as [T, T];
}

type Accent = "emerald" | "violet" | "amber" | "sky" | "rose" | "slate";

const ACCENT_CLASSES: Record<Accent, { border: string; label: string; dot: string }> = {
  emerald: { border: "border-qm-positive-border hover:border-qm-positive",   label: "text-qm-positive", dot: "bg-qm-positive" },
  violet:  { border: "border-qm-premium-border hover:border-qm-premium",     label: "text-qm-premium",  dot: "bg-qm-premium" },
  amber:   { border: "border-qm-warning-border hover:border-qm-warning",     label: "text-qm-warning",  dot: "bg-qm-warning" },
  sky:     { border: "border-qm-premium-border hover:border-qm-premium",     label: "text-qm-premium",  dot: "bg-qm-premium" },
  rose:    { border: "border-qm-danger-border hover:border-qm-danger",       label: "text-qm-danger",   dot: "bg-qm-danger" },
  slate:   { border: "border-qm-border-subtle hover:border-qm-border-subtle", label: "text-qm-faint",   dot: "bg-qm-muted" },
};

// ── Sub-components ────────────────────────────────────────────────────────────

// ── Pattern hero — the centrepiece for premium users ─────────────────────────
function PatternHero({
  emotion, theme, corepattern, reflectedThisWeek,
}: {
  emotion: string | null;
  theme: string | null;
  corepattern: string | null;
  reflectedThisWeek: boolean;
}) {
  const { t } = useTranslation();
  const safePattern = sanitiseCorePattern(corepattern);
  const hasData = emotion || theme || safePattern;
  if (!hasData) return null;

  const bodyText = safePattern
    ? safePattern
    : emotion && theme
    ? `${emotion} keeps showing up — often alongside themes of ${theme.toLowerCase()}.`
    : emotion
    ? `${emotion} has been your most present emotion recently.`
    : `${theme} is the theme appearing most in your entries.`;

  return (
    <div
      className="mb-8 rounded-2xl p-6 sm:p-7"
      style={{
        borderLeft: "2px solid var(--qm-positive)",
        background: "var(--qm-positive-bg)",
        borderRadius: "0 16px 16px 0",
        borderTop: "1px solid var(--qm-positive-border)",
        borderRight: "1px solid var(--qm-positive-border)",
        borderBottom: "1px solid var(--qm-positive-border)",
      }}
    >
      <p className="mb-3 qm-eyebrow text-qm-positive">
        {t.dashboard.yourPatternNow}
      </p>

      <p className="font-display text-[1.2rem] font-medium leading-relaxed text-qm-primary sm:text-[1.3rem]">
        &ldquo;{bodyText}&rdquo;
      </p>

      {(emotion || theme) && (
        <div className="mt-3.5 flex flex-wrap gap-2">
          {emotion && (
            <span className="rounded-full border border-qm-premium-border bg-qm-premium-soft px-2.5 py-1 text-xs text-qm-premium">
              {emotion}
            </span>
          )}
          {theme && (
            <span className="rounded-full border border-qm-positive-border bg-qm-positive-soft px-2.5 py-1 text-xs text-qm-positive">
              {theme}
            </span>
          )}
        </div>
      )}

      <div className="mt-5 flex flex-wrap items-center gap-3">
        <Link
          href="/insights"
          className="text-sm font-medium text-qm-positive transition-colors hover:text-qm-positive-hover"
        >
          {t.dashboard.seeFullInsights} →
        </Link>
        {!reflectedThisWeek && (
          <>
            <span className="text-qm-faint">·</span>
            <Link href="/journal" className="text-sm text-qm-faint transition-colors hover:text-qm-muted">
              {t.dashboard.reflectRecentEntry}
            </Link>
          </>
        )}
      </div>
    </div>
  );
}

// ── Free pattern teaser ───────────────────────────────────────────────────────
function FreePatternTeaser({ entryCount, emotion, theme }: { entryCount: number; emotion: string | null; theme: string | null }) {
  const { t } = useTranslation();
  const hasHint = emotion || theme;

  if (entryCount < 3) {
    return (
      <div className="mb-8 rounded-2xl border border-qm-border-card bg-qm-elevated p-5 sm:p-6">
        <p className="mb-2 qm-eyebrow text-qm-faint">{t.dashboard.yourPatterns}</p>
        <p className="text-sm leading-relaxed text-qm-muted">
          {t.dashboard.freeNudge(CONFIG.appName, 3 - entryCount)}
        </p>
      </div>
    );
  }

  return (
    <div className="mb-8 rounded-2xl border border-qm-border-card bg-qm-elevated p-5 sm:p-6">
      <p className="mb-3 qm-eyebrow text-qm-faint">{t.dashboard.patternForming}</p>
      {hasHint ? (
        <p className="text-sm leading-relaxed text-qm-secondary">
          {t.dashboard.patternTeaser.split("{theme}")[0]}
          <span className="select-none rounded bg-qm-accent-soft px-1 text-qm-primary" style={{ filter: "blur(4px)" }}>
            {emotion ?? theme}
          </span>
          {t.dashboard.patternTeaser.split("{theme}")[1]}
        </p>
      ) : (
        <p className="text-sm leading-relaxed text-qm-secondary">{t.dashboard.patternTeaserNoHint}</p>
      )}
      <Link
        href="/upgrade"
        className="mt-4 inline-flex items-center gap-1.5 rounded-full bg-qm-accent px-4 py-2 text-xs font-semibold text-white transition hover:bg-qm-accent-hover"
      >
        {t.dashboard.unlockInsights}
      </Link>
    </div>
  );
}

// ── Onboarding states ─────────────────────────────────────────────────────────
function WelcomePanel() {
  const { t } = useTranslation();
  return (
    <div className="mb-8 rounded-2xl border border-qm-positive-border bg-qm-positive-bg p-6 sm:p-7">
      <p className="mb-1.5 qm-eyebrow text-qm-positive">{t.dashboard.welcomeTag}</p>
      <h2 className="font-display text-lg font-medium leading-snug text-qm-primary">
        {t.dashboard.welcomeHeading}
      </h2>
      <p className="mt-2 text-sm leading-relaxed text-qm-muted">
        {t.dashboard.welcomeBody(CONFIG.appName)}
      </p>
      <Link
        href="/journal/new"
        className="mt-5 inline-flex items-center gap-2 rounded-full bg-qm-accent px-5 py-2.5 text-sm font-semibold text-white transition hover:bg-qm-accent-hover"
        style={{ boxShadow: "0 6px 20px -4px rgba(139,157,255,0.28)" }}
      >
        {t.dashboard.writeFirstEntry}
      </Link>
      <p className="mt-3 text-xs text-qm-faint">{t.dashboard.welcomePrivacy}</p>
    </div>
  );
}

function PatternStartedCard({ emotion, theme }: { emotion: string | null; theme: string | null }) {
  const { t } = useTranslation();
  return (
    <div className="mb-8 rounded-2xl border border-qm-premium-border bg-qm-premium-bg p-5 sm:p-6">
      <p className="mb-1.5 qm-eyebrow text-qm-premium">{t.dashboard.patternStartedTag}</p>
      <p className="text-sm leading-relaxed text-qm-secondary">
        {t.dashboard.patternStartedBody(emotion, theme)}
      </p>
      <Link href="/journal/new" className="mt-4 inline-flex items-center gap-1.5 text-sm font-medium text-qm-premium transition hover:text-qm-premium-hover">
        {t.dashboard.writeAnotherEntry} →
      </Link>
    </div>
  );
}

function ProgressNudge({ entryCount }: { entryCount: number }) {
  const { t } = useTranslation();
  const remaining = 5 - entryCount;
  if (remaining <= 0) return null;
  return (
    <div className="mb-8 rounded-2xl border border-qm-border-card bg-qm-elevated p-5">
      <div className="mb-2 flex items-center justify-between">
        <p className="qm-eyebrow text-qm-faint">{t.dashboard.patternFormingYours}</p>
        <p className="text-xs text-qm-faint">{entryCount} / 5</p>
      </div>
      <div className="mb-3 h-[2px] w-full rounded-full bg-qm-card">
        <div className="h-[2px] rounded-full bg-qm-positive-muted transition-all" style={{ width: `${(entryCount / 5) * 100}%` }} />
      </div>
      <p className="text-sm text-qm-muted">
        <span className="text-qm-primary">{t.dashboard.moreEntries(remaining)}</span>{" "}
        {t.dashboard.freeNudge(CONFIG.appName, remaining)}
      </p>
    </div>
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────

export default function DashboardClient({ data }: { data: DashboardData }) {
  const { t } = useTranslation();
  const { supabase } = useSupabase();
  const { planType, credits, loading: planLoading } = useUserPlan();

  const [displayName, setDisplayName] = useState<string | null>(null);
  const [mounted, setMounted] = useState(false);
  useEffect(() => { setMounted(true); }, []);

  useEffect(() => {
    supabase.auth.getUser().then(({ data: d }) => {
      setDisplayName(friendlyNameFromUser(d?.user));
    });
  }, [supabase]);

  const isPremium = planType === "PREMIUM" || planType === "TRIAL";
  const isFree = !planLoading && planType === "FREE";
  const reflectionsPaused = isFree && (credits ?? 0) === 0;
  const resetLabel = startOfNextMonth();

  const greeting = displayName
    ? `${greetingByHour(t)}, ${displayName}`
    : greetingByHour(t);

  // Two prompts per day (rotates daily)
  const [promptA, promptB] = useMemo(() => getDailyPrompts(t.dashboard.prompts), [t.dashboard.prompts]);

  const {
    entryCount, writingDays, lastEntryId, lastEntryTitle, lastEntryDate,
    lastEntryHasReflection, lastTopEmotion, lastTopTheme, lastCorepattern,
    wroteToday, reflectedThisWeek,
  } = data;

  const acA = ACCENT_CLASSES[(promptA.accent as Accent) in ACCENT_CLASSES ? (promptA.accent as Accent) : "slate"];
  const acB = ACCENT_CLASSES[(promptB.accent as Accent) in ACCENT_CLASSES ? (promptB.accent as Accent) : "slate"];

  // Thread prompt for the CTA
  const threadPrompt = wroteToday
    ? t.dashboard.alreadyWroteToday
    : lastTopEmotion
    ? t.dashboard.threadPromptEmotion(lastTopEmotion)
    : t.dashboard.threadPromptNoEmotion;

  const lastEntryLabel = lastEntryDate ? friendlyDate(lastEntryDate, mounted, t) : null;

  return (
    <div className="mx-auto max-w-2xl px-5 pb-20 pt-10 text-qm-primary sm:px-6">

      {/* ── Header ─────────────────────────────────────────────────────────── */}
      <div className="mb-8">
        <h1 className="font-display text-[1.9rem] font-medium leading-[1.1] tracking-tight text-qm-primary sm:text-[2.2rem]">
          {greeting}
        </h1>

        {/* Status row */}
        <div className="mt-3 flex flex-wrap items-center gap-x-3 gap-y-1 text-xs text-qm-faint">
          {isPremium ? (
            <span style={{ color: "var(--qm-positive)", opacity: 0.9 }}>{t.dashboard.reflUnlimited}</span>
          ) : reflectionsPaused ? (
            <span>{t.dashboard.reflPaused(resetLabel)}</span>
          ) : (
            <span>
              {t.dashboard.reflRemaining}{" "}
              <span className="text-qm-muted">{planLoading ? "…" : String(credits ?? 0)}</span>
            </span>
          )}

          {entryCount > 0 && (
            <>
              <span style={{ opacity: 0.3 }}>·</span>
              <span>{entryCount} {entryCount === 1 ? t.dashboard.entry : t.dashboard.entries}</span>
            </>
          )}

          {writingDays > 0 && (
            <>
              <span style={{ opacity: 0.3 }}>·</span>
              <span>{t.dashboard.writingDaysLabel(writingDays)}</span>
            </>
          )}
        </div>

        {/* Credit-wall upgrade CTA */}
        {reflectionsPaused && !isPremium && (
          <div className="mt-3 flex items-center gap-3">
            <Link
              href="/upgrade"
              className="inline-flex items-center rounded-full bg-qm-accent px-4 py-1.5 text-xs font-semibold text-white transition hover:bg-qm-accent-hover"
            >
              {t.dashboard.unlockUnlimitedCta}
            </Link>
            <span className="text-xs text-qm-faint">{t.dashboard.trialBadgeFull(PRICING.trialDays)}</span>
          </div>
        )}
      </div>

      {/* ── Onboarding moments ─────────────────────────────────────────────── */}
      {entryCount === 0 && <WelcomePanel />}
      {entryCount === 1 && lastEntryHasReflection && <PatternStartedCard emotion={lastTopEmotion} theme={lastTopTheme} />}
      {entryCount >= 2 && entryCount < 5 && <ProgressNudge entryCount={entryCount} />}

      {/* ── PATTERN HERO (premium) / Teaser (free) ─────────────────────────── */}
      {isPremium && (lastTopEmotion || lastTopTheme || lastCorepattern) && (
        <PatternHero
          emotion={lastTopEmotion}
          theme={lastTopTheme}
          corepattern={lastCorepattern}
          reflectedThisWeek={reflectedThisWeek}
        />
      )}
      {isFree && entryCount >= 5 && (
        <FreePatternTeaser entryCount={entryCount} emotion={lastTopEmotion} theme={lastTopTheme} />
      )}

      {/* ── Write today ────────────────────────────────────────────────────── */}
      <div className="mb-8">
        <p className="mb-3 qm-eyebrow text-qm-faint">
          {wroteToday ? t.dashboard.wroteToday : t.dashboard.todaysPromptsLabel}
        </p>

        <div className="flex flex-col gap-3">
          {/* Primary write CTA — continues from last entry or starts fresh */}
          <Link
            href={buildHref(threadPrompt)}
            className="group rounded-2xl border bg-qm-elevated p-5 transition-all hover:bg-qm-soft"
            style={{ borderColor: "var(--qm-accent-border)" }}
          >
            <div className="mb-2 flex items-center gap-2">
              <span className="h-1.5 w-1.5 rounded-full bg-qm-accent" />
              <span className="text-[10px] font-semibold uppercase tracking-[0.18em] text-qm-accent">
                {wroteToday ? t.dashboard.addToToday : t.dashboard.writeNow}
              </span>
            </div>
            <p className="text-sm font-medium leading-snug text-qm-primary">
              {wroteToday
                ? t.dashboard.dayEvolved
                : lastTopEmotion
                ? t.dashboard.threadBodyWritten(lastEntryLabel ?? "", lastTopEmotion)
                : lastEntryId
                ? t.dashboard.threadBodyWrittenNoEmotion(lastEntryLabel ?? "")
                : t.dashboard.oneHonestSentence}
            </p>
            <p className="mt-3 text-xs font-medium text-qm-accent transition group-hover:text-qm-accent-hover">
              {wroteToday ? t.dashboard.addToToday : t.dashboard.writeNow} →
            </p>
          </Link>

          {/* Two rotating prompts */}
          <div className="grid grid-cols-2 gap-3">
            {[{ prompt: promptA, ac: acA }, { prompt: promptB, ac: acB }].map(({ prompt, ac }) => (
              <Link
                key={prompt.q}
                href={buildHref(prompt.q)}
                className={`group rounded-2xl border bg-qm-elevated p-4 transition-all hover:bg-qm-soft ${ac.border}`}
              >
                <span className={`mb-2.5 block h-1.5 w-1.5 rounded-full ${ac.dot}`} />
                <p className="text-sm font-medium leading-snug text-qm-primary">{prompt.q}</p>
                <p className="mt-1 text-[11px] leading-relaxed text-qm-faint">{prompt.sub}</p>
                <p className={`mt-2.5 text-[11px] font-medium transition ${ac.label}`}>
                  {t.dashboard.startArrow}
                </p>
              </Link>
            ))}
          </div>
        </div>
      </div>

      {/* ── History strip ──────────────────────────────────────────────────── */}
      <div
        className="rounded-2xl border border-qm-border-card"
        style={{ background: "var(--qm-bg-elevated)" }}
      >
        <div className="flex items-center justify-between border-b border-qm-border-card px-5 py-3.5">
          <p className="qm-eyebrow text-qm-faint">{t.dashboard.yourHistory}</p>
          <div className="flex gap-3">
            <Link href="/journal" className="text-xs text-qm-faint transition hover:text-qm-secondary">
              {t.dashboard.allEntriesCta}
            </Link>
            {isPremium && (
              <Link href="/insights" className="text-xs text-qm-positive transition hover:text-qm-positive-hover">
                {t.dashboard.viewInsightsCta}
              </Link>
            )}
          </div>
        </div>

        <div className="grid grid-cols-3 divide-x divide-qm-border-card">
          {[
            { value: entryCount, label: t.dashboard.totalEntries },
            { value: writingDays, label: t.dashboard.writingDays },
            {
              value: lastEntryDate
                ? friendlyDate(lastEntryDate, mounted, t)
                : "—",
              label: t.dashboard.lastEntryLabel,
              suppressHydrationWarning: true,
            },
          ].map(({ value, label, suppressHydrationWarning }) => (
            <div key={label} className="px-5 py-4 text-center">
              <p
                className="text-lg font-medium text-qm-primary"
                suppressHydrationWarning={suppressHydrationWarning}
              >
                {value}
              </p>
              <p className="mt-0.5 text-[11px] text-qm-faint">{label}</p>
            </div>
          ))}
        </div>

        {isPremium && (
          <div className="border-t border-qm-border-card px-5 py-3 text-center">
            <span className="text-xs text-qm-positive">{t.dashboard.reflUnlimited}</span>
          </div>
        )}
      </div>

    </div>
  );
}
