// app/(protected)/dashboard/DashboardClient.tsx
"use client";

import Link from "next/link";
import { useCallback, useEffect, useMemo, useState } from "react";
import { useSupabase } from "@/app/components/SupabaseSessionProvider";
import { useUserPlan } from "@/app/components/useUserPlan";
import type { DashboardData } from "./page";
import { PRICING } from "@/app/lib/pricing";
import { ERRORS, NAV, JOURNAL } from "@/app/lib/copy";

// ── Helpers ───────────────────────────────────────────────────────────────────

function titleOrUntitled(title: string | null) {
  return title?.trim() ? title.trim() : JOURNAL.untitledEntry;
}

function friendlyNameFromUser(user: any): string | null {
  const md = user?.user_metadata ?? {};
  // Auto-generated usernames look like "xidohi8055" — all lowercase letters then digits, no spaces
  const isAutoGenerated = (s: string) => /^[a-z]+\d+$/i.test(s.trim()) && !s.includes(" ");
  const emailPrefix = user?.email ? String(user.email).split("@")[0] : null;
  const raw = [
    md.full_name,
    md.name,
    md.display_name,
    isAutoGenerated(String(md.username ?? "")) ? null : md.username,
    emailPrefix && isAutoGenerated(emailPrefix) ? null : emailPrefix,
  ].filter(Boolean).map(String)[0] ?? "";
  const clean = raw.trim().replace(/\s+/g, " ").slice(0, 24);
  return clean || null;
}

function buildHref(prompt: string) {
  return `/journal/new?prompt=${encodeURIComponent(prompt)}`;
}

function greetingByHour() {
  const h = new Date().getHours();
  if (h < 12) return "Good morning";
  if (h < 18) return "Good afternoon";
  return "Good evening";
}

function friendlyDate(iso: string, isMounted = false) {
  const d = new Date(iso);
  const today = new Date();
  const yesterday = new Date(today);
  yesterday.setDate(today.getDate() - 1);
  const isoDate = (x: Date) => x.toISOString().slice(0, 10);
  if (isoDate(d) === isoDate(today)) return "today";
  if (isoDate(d) === isoDate(yesterday)) return "yesterday";
  return isMounted ? d.toLocaleDateString(undefined, { month: "short", day: "numeric" }) : iso.slice(0, 10);
}

function startOfNextMonth() {
  const d = new Date();
  return new Date(d.getFullYear(), d.getMonth() + 1, 1)
    .toLocaleDateString(undefined, { month: "short", day: "numeric" });
}

// Sanitise AI-generated corepattern — strip anything that references test data
// or looks like a raw NLP analysis sentence rather than a human-readable insight.
function sanitiseCorePattern(raw: string | null): string | null {
  if (!raw) return null;
  // If the pattern contains typical test-data markers, suppress it
  const lower = raw.toLowerCase();
  if (
    lower.includes("for test") ||
    lower.includes("as indicated by") ||
    lower.includes("your phrase") ||
    lower.length < 15
  ) {
    return null;
  }
  return raw;
}

const PROMPT_POOL = [
  { q: "How is your body feeling right now?", sub: "Tension, calm, tired, restless — anything you notice.", accent: "emerald" },
  { q: "What is one thing occupying your mind?", sub: "One sentence is enough.", accent: "violet" },
  { q: "What are you avoiding thinking about?", sub: "You don't have to solve it — just name it.", accent: "amber" },
  { q: "What do you need more of right now?", sub: "Rest, space, connection, clarity — anything.", accent: "sky" },
  { q: "What felt heavy this week?", sub: "No need to explain why.", accent: "rose" },
  { q: "What are you proud of, even quietly?", sub: "Small things count.", accent: "emerald" },
  { q: "Just free write", sub: "No structure. No rules. Start anywhere.", accent: "slate" },
];

function getDailyPrompts(): typeof PROMPT_POOL {
  const day = new Date().getDay();
  const start = day % PROMPT_POOL.length;
  return [
    PROMPT_POOL[start % PROMPT_POOL.length],
    PROMPT_POOL[(start + 1) % PROMPT_POOL.length],
    PROMPT_POOL[(start + 2) % PROMPT_POOL.length],
  ];
}

// Map accent name → Tailwind classes
const ACCENT_CLASSES: Record<string, { border: string; label: string; dot: string; arrow: string }> = {
  emerald: {
    border: "border-emerald-500/20 hover:border-emerald-500/40",
    label: "text-emerald-400/60",
    dot: "bg-emerald-500",
    arrow: "text-emerald-400 group-hover:text-emerald-300",
  },
  violet: {
    border: "border-violet-500/20 hover:border-violet-500/40",
    label: "text-violet-400/60",
    dot: "bg-violet-500",
    arrow: "text-violet-400 group-hover:text-violet-300",
  },
  amber: {
    border: "border-amber-500/20 hover:border-amber-500/40",
    label: "text-amber-400/60",
    dot: "bg-amber-500",
    arrow: "text-amber-400 group-hover:text-amber-300",
  },
  sky: {
    border: "border-violet-500/20 hover:border-violet-500/40",
    label: "text-violet-400/60",
    dot: "bg-violet-500",
    arrow: "text-violet-400 group-hover:text-violet-300",
  },
  rose: {
    border: "border-rose-500/20 hover:border-rose-500/40",
    label: "text-rose-400/60",
    dot: "bg-rose-500",
    arrow: "text-rose-400 group-hover:text-rose-300",
  },
  slate: {
    border: "border-slate-700/60 hover:border-slate-600",
    label: "text-slate-500",
    dot: "bg-slate-500",
    arrow: "text-slate-400 group-hover:text-slate-300",
  },
};

// ── Sub-components ────────────────────────────────────────────────────────────

// ── Premium insight card ──────────────────────────────────────────────────────

function PremiumInsightCard({
  emotion,
  theme,
  corepattern,
  reflectedThisWeek,
}: {
  emotion: string | null;
  theme: string | null;
  corepattern: string | null;
  reflectedThisWeek: boolean;
}) {
  const safePattern = sanitiseCorePattern(corepattern);
  const hasData = emotion || theme || safePattern;
  if (!hasData) return null;

  const bodyText = safePattern
    ? safePattern
    : emotion && theme
    ? `${emotion} keeps showing up — often alongside themes of ${theme.toLowerCase()}.`
    : emotion
    ? `${emotion} has been your most present emotion recently.`
    : `${theme} is the theme appearing most in your entries.`;

  return (
    <div className="rounded-2xl border border-emerald-500/20 bg-gradient-to-br from-emerald-500/[0.06] to-transparent p-5 sm:p-6">
      <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-emerald-500/70">
        Your pattern right now
      </p>

      <p className="font-display text-base font-medium leading-relaxed text-slate-100 sm:text-[17px]">
        &ldquo;{bodyText}&rdquo;
      </p>

      {(emotion || theme) && (
        <div className="mt-3 flex flex-wrap gap-2">
          {emotion && (
            <span className="rounded-full border border-violet-500/20 bg-violet-500/10 px-2.5 py-0.5 text-xs text-violet-300">
              {emotion}
            </span>
          )}
          {theme && (
            <span className="rounded-full border border-emerald-500/20 bg-emerald-500/10 px-2.5 py-0.5 text-xs text-emerald-300">
              {theme}
            </span>
          )}
        </div>
      )}

      <div className="mt-4 flex flex-wrap items-center gap-3">
        <Link
          href="/insights"
          className="text-xs font-medium text-emerald-400 transition hover:text-emerald-300"
        >
          See full insights →
        </Link>
        {!reflectedThisWeek && (
          <>
            <span className="text-xs text-slate-700">·</span>
            <Link
              href="/journal"
              className="text-xs text-slate-500 transition hover:text-slate-400"
            >
              Reflect on a recent entry
            </Link>
          </>
        )}
      </div>
    </div>
  );
}

// ── Free insight teaser ───────────────────────────────────────────────────────

function FreeInsightTeaser({
  entryCount,
  emotion,
  theme,
}: {
  entryCount: number;
  emotion: string | null;
  theme: string | null;
}) {
  const hasHint = emotion || theme;

  if (entryCount < 3) {
    return (
      <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5 sm:p-6">
        <p className="mb-2 text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">
          Your patterns
        </p>
        <p className="text-sm leading-relaxed text-slate-400">
          Write{" "}
          <span className="text-slate-200">
            {3 - entryCount} more {3 - entryCount === 1 ? "entry" : "entries"}
          </span>{" "}
          and Quiet Mirror will start noticing what quietly repeats across your writing.
        </p>
      </div>
    );
  }

  return (
    <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5 sm:p-6">
      <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">
        A pattern is forming
      </p>

      {hasHint ? (
        <p className="text-sm leading-relaxed text-slate-300">
          Across your entries, there may be a recurring thread around{" "}
          <span className="select-none rounded bg-white/10 px-1 text-white blur-[5px]">
            {emotion ?? theme}
          </span>
          . Premium helps you see it clearly.
        </p>
      ) : (
        <p className="text-sm leading-relaxed text-slate-300">
          Quiet Mirror has noticed a recurring thread in your entries. Premium helps
          you see what quietly repeats.
        </p>
      )}

      <Link
        href="/upgrade"
        className="mt-4 inline-flex items-center gap-1.5 rounded-full bg-[color:var(--hvn-accent-mint)] px-4 py-2 text-xs font-semibold text-white transition hover:bg-[color:var(--hvn-accent-mint-hover)]"
      >
        Unlock insights →
      </Link>
    </div>
  );
}

// ── Thread card ───────────────────────────────────────────────────────────────

function ThreadCard({
  lastEntryId,
  lastEntryTitle,
  lastEntryDate,
  lastTopEmotion,
  wroteToday,
}: {
  lastEntryId: string | null;
  lastEntryTitle: string | null;
  lastEntryDate: string | null;
  lastTopEmotion: string | null;
  wroteToday: boolean;
}) {
  const [mounted, setMounted] = useState(false);
  useEffect(() => { setMounted(true); }, []);
  const when = lastEntryDate ? friendlyDate(lastEntryDate, mounted) : null;
  const title = titleOrUntitled(lastEntryTitle);

  const sectionLabel = wroteToday
    ? "You wrote today"
    : lastEntryId
    ? "Pick up the thread"
    : "Start here";

  // Don't echo the raw entry title into the prompt body — feels broken with test titles
  const body = wroteToday
    ? "How has the day evolved since you last wrote?"
    : lastEntryId && lastTopEmotion
    ? `You wrote ${when}. ${lastTopEmotion} was present. Has anything shifted?`
    : lastEntryId
    ? `You last wrote ${when}. Has anything softened since?`
    : "One honest sentence is always enough to start.";

  const threadPrompt = wroteToday
    ? "You've already written today — how has the day evolved?"
    : lastTopEmotion
    ? `Following up on your last entry — ${lastTopEmotion} was present. Has anything shifted?`
    : `Following up on your last entry — has anything softened since you wrote?`;

  return (
    <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5">
      <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">
        {sectionLabel}
      </p>
      <p className="mt-2 text-sm font-medium leading-snug text-slate-200">
        {body}
      </p>

      <div className="mt-4 flex flex-wrap gap-2">
        <Link
          href={buildHref(threadPrompt)}
          className="inline-flex rounded-full bg-[color:var(--hvn-accent-mint)] px-4 py-2 text-sm font-semibold text-white shadow-sm transition hover:bg-[color:var(--hvn-accent-mint-hover)]"
        >
          {wroteToday ? "Add to today" : "Write now"}
        </Link>

        {lastEntryId && (
          <Link
            href={`/journal/${lastEntryId}`}
            className="inline-flex rounded-full border border-white/[0.08] bg-white/[0.03] px-4 py-2 text-sm font-medium text-slate-300 transition hover:bg-white/[0.07]"
          >
            Open last entry
          </Link>
        )}
      </div>
    </div>
  );
}

// ── Welcome panel (zero entries) ──────────────────────────────────────────────

function WelcomePanel() {
  return (
    <div className="mb-8 rounded-2xl border border-emerald-500/20 bg-emerald-500/[0.04] p-6">
      <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-emerald-500/70">
        Welcome to Quiet Mirror
      </p>
      <h2 className="font-display text-lg font-semibold leading-snug text-white">
        This is your private space to think out loud.
      </h2>
      <p className="mt-2 text-sm leading-relaxed text-slate-400">
        Write what&apos;s actually going on — Quiet Mirror reads it, reflects it back
        gently, and starts noticing what quietly repeats across your entries over
        time. One sentence is always enough to start.
      </p>
      <Link
        href="/journal/new"
        className="mt-5 inline-flex items-center gap-2 rounded-full bg-[color:var(--hvn-accent-mint)] px-5 py-2.5 text-sm font-semibold text-white shadow-sm transition hover:bg-[color:var(--hvn-accent-mint-hover)]"
      >
        Write your first entry →
      </Link>
      <p className="mt-3 text-xs text-slate-600">
        Takes less than a minute · stays private · never trains AI
      </p>
    </div>
  );
}

// ── Pattern started (1 entry with reflection) ─────────────────────────────────

function PatternStartedCard({
  emotion,
  theme,
}: {
  emotion: string | null;
  theme: string | null;
}) {
  return (
    <div className="mb-8 rounded-2xl border border-violet-500/20 bg-violet-500/[0.04] p-6">
      <p className="mb-1 text-[10px] font-semibold uppercase tracking-[0.2em] text-violet-400/70">
        Your pattern history has started
      </p>
      <p className="text-sm leading-relaxed text-slate-300">
        Quiet Mirror has your first reflection.{" "}
        {emotion || theme ? (
          <>
            It noticed{" "}
            <span className="text-slate-100">{emotion ?? theme}</span> in what
            you wrote.{" "}
          </>
        ) : null}
        The more you write, the more clearly the patterns will show.
      </p>
      <Link
        href="/journal/new"
        className="mt-4 inline-flex items-center gap-2 text-xs font-medium text-violet-400 transition hover:text-violet-300"
      >
        Write another entry →
      </Link>
    </div>
  );
}

// ── Progress nudge (2–4 entries) ──────────────────────────────────────────────

function ProgressNudge({ entryCount }: { entryCount: number }) {
  const remaining = 5 - entryCount;
  if (remaining <= 0) return null;

  return (
    <div className="mb-8 rounded-2xl border border-slate-800/60 bg-slate-900/30 p-5">
      <div className="mb-2 flex items-center justify-between">
        <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">
          Your pattern is forming
        </p>
        <p className="text-xs text-slate-600">
          {entryCount} / 5 entries
        </p>
      </div>
      <div className="mb-3 h-1 w-full rounded-full bg-slate-800">
        <div
          className="h-1 rounded-full bg-emerald-500/60 transition-all"
          style={{ width: `${(entryCount / 5) * 100}%` }}
        />
      </div>
      <p className="text-sm text-slate-400">
        <span className="text-slate-200">
          {remaining} more {remaining === 1 ? "entry" : "entries"}
        </span>{" "}
        and Quiet Mirror will start showing you what quietly repeats across your
        writing.
      </p>
    </div>
  );
}

// ── Main ──────────────────────────────────────────────────────────────────────

export default function DashboardClient({ data }: { data: DashboardData }) {
  const { supabase } = useSupabase();
  const { planType, credits, loading: planLoading } = useUserPlan();

  const [displayName, setDisplayName] = useState<string | null>(null);
  const [mounted, setMounted] = useState(false);
  useEffect(() => { setMounted(true); }, []);

  useEffect(() => {
    supabase.auth.getUser().then(({ data: d }) => {
      setDisplayName(friendlyNameFromUser(d?.user));
    });
  }, [supabase]);

  const isPremium = planType === "PREMIUM" || planType === "TRIAL";
  const isFree = !planLoading && planType === "FREE";
  const reflectionsPaused = isFree && (credits ?? 0) === 0;
  const resetLabel = startOfNextMonth();
  const readablePlan = isPremium
    ? planType === "TRIAL" ? "Trial" : "Premium"
    : "Free";

  const greeting = displayName
    ? `${greetingByHour()}, ${displayName}`
    : greetingByHour();

  const prompts = useMemo(() => getDailyPrompts(), []);

  const {
    entryCount, writingDays, lastEntryId, lastEntryTitle, lastEntryDate,
    lastEntryHasReflection, lastTopEmotion, lastTopTheme, lastCorepattern,
    wroteToday, reflectedThisWeek,
  } = data;

  const subline = useMemo(() => {
    if (entryCount === 0) return JOURNAL.emptyStateNudge;
    if (wroteToday) return "You've written today.";
    return "Choose a prompt to begin.";
  }, [entryCount, wroteToday]);

  return (
    <div className="mx-auto max-w-5xl px-5 pb-20 pt-10 text-slate-200 sm:px-6">

      {/* ── Header ── */}
      <div className="mb-8">
        <div className="flex flex-wrap items-start justify-between gap-3">
          <div className="space-y-1">
            {/* ✅ Fraunces serif on the greeting — most personal line in the app */}
            <h1 className="font-display text-3xl font-semibold tracking-tight text-white sm:text-4xl">
              {greeting}
            </h1>
            <p className="text-sm text-slate-500">{subline}</p>
          </div>
        </div>

        {/* ✅ Replaced debug-style pill badges with a subtle single-line status row */}
        <div className="mt-4 flex flex-wrap items-center gap-x-4 gap-y-1 text-xs text-slate-600">
          <span>
            Plan:{" "}
            <span className={isPremium ? "text-emerald-400" : "text-slate-400"}>
              {readablePlan}
            </span>
          </span>

          <span className="text-slate-800">·</span>

          {isPremium ? (
            <span>
              Reflections: <span className="text-emerald-400">unlimited</span>
            </span>
          ) : reflectionsPaused ? (
            <span>
              Reflections paused —{" "}
              <span className="text-slate-500">returns {resetLabel}</span>
            </span>
          ) : (
            <span>
              Reflections remaining:{" "}
              <span className="text-slate-400">
                {planLoading ? "…" : String(credits ?? 0)}
              </span>
            </span>
          )}

          {entryCount > 0 && (
            <>
              <span className="text-slate-800">·</span>
              <span>
                {entryCount} {entryCount === 1 ? "entry" : "entries"}
              </span>
            </>
          )}
        </div>

        {reflectionsPaused && (
          <p className="mt-1.5 text-xs text-slate-700">
            You can always write freely — reflections return {resetLabel}.
          </p>
        )}

        {/* Bug #23 fix: upgrade CTA at 0-credit wall — highest-intent moment */}
        {reflectionsPaused && !isPremium && (
          <div className="mt-3 flex items-center gap-3">
            <Link
              href="/upgrade"
              className="inline-flex items-center rounded-full bg-[color:var(--hvn-accent-mint)] px-4 py-1.5 text-xs font-semibold text-white hover:bg-[color:var(--hvn-accent-mint-hover)] transition-colors"
            >
              Unlock unlimited reflections →
            </Link>
            <span className="text-xs text-slate-700">{PRICING.trialDays}-day full refund · Cancel anytime</span>
          </div>
        )}
      </div>

      {/* ── Onboarding moments ── */}
      {entryCount === 0 && <WelcomePanel />}

      {entryCount === 1 && lastEntryHasReflection && (
        <PatternStartedCard emotion={lastTopEmotion} theme={lastTopTheme} />
      )}

      {entryCount >= 2 && entryCount < 5 && (
        <ProgressNudge entryCount={entryCount} />
      )}

      {/* ── Premium insight / Free teaser ── */}
      {isPremium && (lastTopEmotion || lastTopTheme || lastCorepattern) && (
        <div className="mb-8">
          <PremiumInsightCard
            emotion={lastTopEmotion}
            theme={lastTopTheme}
            corepattern={lastCorepattern}
            reflectedThisWeek={reflectedThisWeek}
          />
        </div>
      )}

      {isFree && entryCount >= 5 && (
        <div className="mb-8">
          <FreeInsightTeaser
            entryCount={entryCount}
            emotion={lastTopEmotion}
            theme={lastTopTheme}
          />
        </div>
      )}

      {/* ── Daily prompts ── */}
      <div className="mb-6">
        <p className="mb-3 text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-600">
          Today&apos;s prompts
        </p>

        <div className="grid gap-3 sm:grid-cols-3">
          {prompts.map((c) => {
            const ac = ACCENT_CLASSES[c.accent] ?? ACCENT_CLASSES.slate;
            return (
              <Link
                key={c.q}
                href={buildHref(c.q)}
                className={`group rounded-2xl border bg-white/[0.02] p-5 transition hover:bg-white/[0.05] ${ac.border}`}
              >
                {/* ✅ Colored dot per-prompt for visual differentiation */}
                <span className={`mb-3 block h-1.5 w-1.5 rounded-full ${ac.dot}`} />
                <p className="font-medium leading-snug text-slate-100 transition group-hover:text-white">
                  {c.q}
                </p>
                <p className="mt-1.5 text-xs leading-relaxed text-slate-500">{c.sub}</p>
                <p className="mt-3 text-xs font-medium transition text-emerald-400 group-hover:text-emerald-300">
                  Start →
                </p>
              </Link>
            );
          })}
        </div>
      </div>

      {/* ── Thread + history row ── */}
      <div className="grid gap-4 sm:grid-cols-2">

        <ThreadCard
          lastEntryId={lastEntryId}
          lastEntryTitle={lastEntryTitle}
          lastEntryDate={lastEntryDate}
          lastTopEmotion={lastTopEmotion}
          wroteToday={wroteToday}
        />

        {/* ✅ History card — cleaner, less "settings panel" feel */}
        <div className="rounded-2xl border border-white/[0.08] bg-white/[0.03] p-5">
          <p className="text-[10px] font-semibold uppercase tracking-[0.2em] text-slate-500">
            Your history
          </p>

          <div className="mt-4 space-y-2.5">
            <div className="flex items-center justify-between text-sm">
              <span className="text-slate-500">Total entries</span>
              <span className="font-medium text-slate-200">{entryCount}</span>
            </div>
            <div className="flex items-center justify-between text-sm">
              <span className="text-slate-500">Writing days</span>
              <span className="font-medium text-slate-200">{writingDays}</span>
            </div>
            {lastEntryDate && (
              <div className="flex items-center justify-between text-sm">
                <span className="text-slate-500">Last entry</span>
                <span className="font-medium text-slate-200" suppressHydrationWarning>
                  {friendlyDate(lastEntryDate, mounted)}
                </span>
              </div>
            )}
            {isPremium && (
              <div className="flex items-center justify-between text-sm">
                <span className="text-slate-500">Reflections</span>
                <span className="font-medium text-emerald-400">Unlimited</span>
              </div>
            )}
          </div>

          <div className="mt-5 flex flex-wrap gap-3 border-t border-white/[0.05] pt-4">
            <Link
              href="/journal"
              className="text-xs text-slate-500 transition hover:text-slate-300"
            >
              All entries →
            </Link>
            {isPremium && (
              <Link
                href="/insights"
                className="text-xs text-emerald-500/70 transition hover:text-emerald-400"
              >
                View insights →
              </Link>
            )}
          </div>
        </div>
      </div>

    </div>
  );
}
